# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'Reso' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Reso
pod 'Firebase'
pod 'Firebase/Auth'
pod 'Firebase/Database'
pod 'Firebase/Messaging'

  target 'ResoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ResoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
